### ISSUE TITLE
YAML reaction incorrectly parsing decimal stoichiometry as float

### ISSUE THREAD

**Issue by jonls** [zhanglab/psamm#124]
The following model fails when running FBA. It appears that the `0.001` stoichiometric value for `a` in the `biomass` is parsed as a `float` while the `0.5` stoichiometric value for `a` in `rxn_1` is parsed as `Decimal`. When running FBA, these two values should be added to construct the LP equations but `float` and `Decimal` cannot be added. This would be solved if the stoichiometric values for the YAML reaction (`biomass` in this case) were correctly parsed as `Decimal`.

``` yaml
biomass: biomass
reactions:
  - id: rxn_1
    equation: (0.5) a => (0.5) c
  - id: biomass
    equation:
      left:
        - id: a
          value: 0.001
      right:
        - id: b
          value: 0.002
```
