### ISSUE TITLE
When loading a medium YAML file the extracellular compartment should be the default compartment

### ISSUE THREAD

**Issue by jonls** [zhanglab/psamm#68]
Currently the compartment must be specified twice:
``` yaml
extracellular: e
media:
  - compartment: e
    compounds:
      - id: abc
```

Instead, the media should by default use the extracellular compartment for compounds.
